### PR TITLE
FIX: Runtime type errors

### PR DESCRIPTION
**Pull request by L3odr0id**
There are several lines with typecast errors. The errors appear sometimes in runtime

### CODE REVIEW

**Comment by poka-IT** [comment]
Yes, if you check the 2 others MR, you will see we are fixing the same thing, but @RomeroYang doesn't seem to want to fix this problem...

**Comment by L3odr0id** [comment]
Oh, I see. That's sad

**Comment by RomeroYang** [comment]
The typecast was auto generated by another developer while doing null-safety rebuild with script. I don't know why but it works well in polkawallet since then 😂.

**Comment by L3odr0id** [comment]
@RomeroYang , actually the bug in `lib/api/apiAssets.dart` was not fixed in #35.
Please, check this: https://github.com/L3odr0id/polkawallet_sdk/commit/3eb28f1dfcfd4d122c50ba70e6c7406cced5a0b5

**Pull request merged**
